workflows:
  ios:
    name: Build iOS app
    environment:
      vars:
        - key: EXPO_TOKEN
          value: $ExQ-w_hkctCu3ZktDbny9SCe-yRi9OjWpKHZYarx
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build iOS
        script: |
          cd ios
          pod install
          cd ..
          react-native run-ios

  android:
    name: Build Android app
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build Android
        script: |
          react-native run-android

