workflows:
  ios:
    name: Build iOS app
    max_build_duration: 60
    environment:
      vars:
        - key: EXPO_TOKEN
          value: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build iOS
        script: |
          cd ios
          pod install
          cd ..
          react-native run-ios
  android:
    name: Build Android app
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build Android
        script: |
          react-native run-android
